project:
  type: book
  output-dir: build
  execute-dir: file

book:
  title: 'PHES-ODM Sharing Library Manual'
  author: 'OHRI'
  chapters:
    - index.qmd
    - chapters/install.qmd
    - chapters/getting-started.qmd
    - chapters/cli-reference.qmd
    - chapters/cli-usage.qmd
    - api-reference/index.qmd
    - chapters/api-usage.qmd
  appendices:
    - chapters/schemas.qmd
    - chapters/python.qmd
    - chapters/sqlite.qmd

quartodoc:
  renderer: _renderer.py
  style: single-page
  parser: sphinx
  package: odm_sharing
  dir: api-reference
  sections:
    - title: API Reference
    - contents:
        - sharing.extract
        - sharing.parse
        - sharing.connect
        - sharing.get_data
        - sharing.get_counts
        - sharing.get_columns

theme:
  - default
  - assets/style.scss

pdf-engine: pdflatex
toc: true
toc-depth: 2
