project:
  type: book

book:
  title: 'PHES-ODM Sharing Library Manual'
  author: 'OHRI'
  chapters:
    - index.qmd
    - install.qmd
    - getting-started.qmd
    - cli.qmd
    - reference/index.qmd
  appendices:
    - schemas.qmd
    - python.qmd
    - sqlite.qmd

quartodoc:
  style: single-page
  parser: sphinx
  package: odm_sharing
  sections:
    - title: API
    - contents:
        - sharing.extract
        - sharing.parse
        - sharing.connect
        - sharing.get_data
        - sharing.get_counts
        - sharing.get_columns

pdf-engine: pdflatex
toc: true
