# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Pylint

on:
  push:
    paths:
      - 'sharing/**'
  pull_request:
    paths:
      - 'sharing/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
    - name: Test with pytest
      run: |
        if [ -d tests ] || [ -d test ] || [ -d sharing_tests ]; then python -m pytest; fi
